### ISSUE TITLE
Upcoming Update

### ISSUE THREAD

**Issue by CriticalFlaw** [raysfire/rayshud#123]
- [ ] [Floating health value is not visible](https://github.com/raysfire/rayshud/issues/118)
   - https://steamcommunity.com/groups/rayshud/discussions/0/1471967615880712835/
- [ ] [Element scaling for smaller and larger resolutions](https://github.com/raysfire/rayshud/issues/41)
- [ ] [Implement Clovervidia's Closed Captions](https://github.com/raysfire/rayshud/issues/125)
- [ ] [Buttons overlapped when previewing an item in fullscreen](https://github.com/ValveSoftware/Source-1-Games/issues/2443)
