### ISSUE TITLE
4:3 Fixes Checklist

### ISSUE THREAD

**Issue by CriticalFlaw** [raysfire/rayshud#92]
There are several issues when in the 4:3 resolution with many of the elements not displaying properly. I'm aware that there are files that fix the scoreboard and tournament spectator in the customization folder, but some notable changes need to be implemented into the base files
- [ ] Misplaced elements on the main menu and in-game HUD
- [x] Killstreak, Ammo/Health and Critical Counter not being visible
- [ ] Possibly related to some instances of the TargetID not being visible (https://github.com/raysfire/rayshud/issues/84)

**Comment by CriticalFlaw** [comment]
Unable to reproduce any of these issues in 4:3 resolution

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/raysfire/rayshud/commit/9dde8a127260cfb8125ba891e112634b4437cc3b
